"use client";

import { ArrowLeft, ArrowRight, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { runAliyunCaptcha } from "@/lib/aliyun-captcha";
import { resetPassword, sendForgotPasswordCode } from "@/lib/auth";

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState(""); const [countdown, setCountdown] = useState(0); const [pending, setPending] = useState(false); const [sending, setSending] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [show, setShow] = useState(false);
  useEffect(() => { if (!countdown) return; const timer = window.setTimeout(() => setCountdown((v) => Math.max(v - 1, 0)), 1000); return () => window.clearTimeout(timer); }, [countdown]);
  async function sendCode() { setError(""); setNotice(""); if (!email.includes("@")) { setError("请先输入有效的邮箱地址"); return; } setSending(true); try { const captcha = await runAliyunCaptcha({ prefix: process.env.NEXT_PUBLIC_ALIYUN_CAPTCHA_PREFIX ?? "", sceneId: process.env.NEXT_PUBLIC_ALIYUN_CAPTCHA_SCENE_ID ?? "", region: "cn" }); const result = await sendForgotPasswordCode({ email: email.trim(), captcha_verify_param: captcha }); setCountdown(Math.max(result.retry_after_seconds, 50)); setNotice(result.message); } catch (e) { setError(e instanceof Error ? e.message : "验证码发送失败"); } finally { setSending(false); } }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setPending(true); const data = new FormData(event.currentTarget); try { await resetPassword({ email: email.trim(), email_code: String(data.get("code") ?? "").trim(), password: String(data.get("password") ?? "") }); window.location.href = "/"; } catch (e) { setError(e instanceof Error ? e.message : "重置失败，请稍后重试"); } finally { setPending(false); } }
  const PasswordIcon = show ? EyeOff : Eye;
  return <main className="relative min-h-screen overflow-hidden px-5 py-8 sm:px-8 lg:grid lg:place-items-center lg:py-12"><section className="mx-auto w-full max-w-xl rounded-[2rem] border bg-white/90 p-7 shadow-xl sm:p-12"><Link href="/login" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4" />返回登录</Link><p className="mt-12 text-sm text-primary">ACCOUNT RECOVERY</p><h1 className="mt-3 text-4xl font-semibold">找回密码</h1><p className="mt-3 text-sm text-muted-foreground">使用已注册邮箱接收验证码，设置新的登录密码。</p><form onSubmit={submit} className="mt-9 space-y-5"><label className="block text-sm font-medium">邮箱<div className="relative mt-2"><Mail className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-12 pl-10" placeholder="name@example.com" /></div></label><div><label className="text-sm font-medium">邮箱验证码</label><div className="mt-2 flex gap-2"><div className="relative min-w-0 flex-1"><ShieldCheck className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input required name="code" maxLength={6} pattern="[0-9]{6}" className="h-12 pl-10 font-mono tracking-[0.25em]" placeholder="6 位验证码" /></div><Button type="button" variant="outline" disabled={sending || countdown > 0} onClick={sendCode} className="h-12 min-w-28">{sending ? "验证中…" : countdown ? `${countdown}s` : "获取验证码"}</Button></div></div><label className="block text-sm font-medium">新密码<div className="relative mt-2"><LockKeyhole className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input required name="password" minLength={8} type={show ? "text" : "password"} className="h-12 pl-10 pr-11" placeholder="至少 8 位，包含字母和数字" /><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2"><PasswordIcon className="size-4 text-muted-foreground" /></button></div></label>{error && <p role="alert" className="rounded-xl border border-destructive/20 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</p>}{notice && <p className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm text-primary">{notice}</p>}<Button disabled={pending} className="h-12 w-full">{pending ? "正在保存…" : "重置密码"}<ArrowRight /></Button></form></section></main>;
}
